"""Rule-based SQL sanity checker: detect structural mismatches between
the user's query intent and the generated SQL.

Uses deterministic rules for fast, reliable mismatch detection.
Runs BEFORE execution and triggers re-generation when a clear
structural error is detected.
"""
from __future__ import annotations

import re
from typing import Any

# Columns that the user might ask about, mapped from Japanese keywords
_KEYWORD_TO_COLUMNS: list[tuple[re.Pattern[str], set[str]]] = [
    (re.compile(r"格子定数|lattice.constant|lattice_a", re.I),
     {"lattice_a", "lattice_b", "lattice_c"}),
    (re.compile(r"形成エネルギー|formation.energy", re.I),
     {"formation_energy_per_atom"}),
    (re.compile(r"バルクモジュラス|bulk.modulus", re.I),
     {"bulk_modulus", "bulk_modulus_vrh", "value"}),
    (re.compile(r"せん断|shear.modulus", re.I),
     {"shear_modulus", "shear_modulus_vrh", "value"}),
    (re.compile(r"バンドギャップ|band.gap", re.I),
     {"band_gap"}),
    (re.compile(r"安定|stable|energy.above.hull", re.I),
     {"is_stable", "energy_above_hull"}),
    (re.compile(r"体積|volume", re.I),
     {"volume_per_atom", "volume"}),
    (re.compile(r"空間群|space.group", re.I),
     {"space_group", "space_group_number"}),
    (re.compile(r"化学式|formula|組成", re.I),
     {"formula", "reduced_formula", "chemical_system"}),
]


def _extract_select_columns(sql: str) -> set[str]:
    """Extract column names/aliases from the SELECT clause."""
    m = re.match(r"SELECT\s+(.*?)\s+FROM\s", sql, re.I | re.DOTALL)
    if not m:
        return set()
    select_clause = m.group(1)
    cols = set()
    for part in select_clause.split(","):
        part = part.strip()
        # AS alias
        alias_match = re.search(r"\bAS\s+(\w+)", part, re.I)
        if alias_match:
            cols.add(alias_match.group(1).lower())
        # table.column
        col_match = re.search(r"\.(\w+)\s*$", part)
        if col_match:
            cols.add(col_match.group(1).lower())
        # Standalone column
        if re.match(r"^\w+$", part):
            cols.add(part.lower())
    return cols


def _has_group_by(sql: str) -> bool:
    return bool(re.search(r"\bGROUP\s+BY\b", sql, re.I))


def _has_count(sql: str) -> bool:
    return bool(re.search(r"\bCOUNT\s*\(", sql, re.I))


def _has_avg(sql: str) -> bool:
    return bool(re.search(r"\bAVG\s*\(", sql, re.I))


def check_sql_sanity(
    user_query: str,
    generated_sql: str,
    query_type: str,
) -> dict[str, Any]:
    """Check if the generated SQL structurally matches the user's intent.

    Parameters
    ----------
    user_query : str
        The original user question.
    generated_sql : str
        The SQL generated by the LLM.
    query_type : str
        The classified query type: "list", "count", "aggregate", "top_n".

    Returns
    -------
    dict with:
      - sane: bool (True if no issues detected)
      - issues: list[str] (descriptions of detected problems)
      - correction_hints: str (hints for regeneration prompt)
    """
    if not generated_sql.strip():
        return {"sane": True, "issues": [], "correction_hints": ""}

    issues: list[str] = []
    sql_upper = generated_sql.upper()
    select_cols = _extract_select_columns(generated_sql)

    # Rule 1: query_type="list" but SQL has GROUP BY + aggregates (not just ORDER BY)
    if query_type == "list" and _has_group_by(generated_sql):
        # Exception: GROUP BY is ok if there's no aggregate function
        # (some LLMs use GROUP BY as dedup instead of DISTINCT)
        if _has_count(generated_sql) or _has_avg(generated_sql):
            issues.append(
                "Query type is 'list' (individual rows) but SQL uses GROUP BY "
                "with aggregate functions. Remove GROUP BY and return individual rows."
            )

    # Rule 2: query_type="list" but SQL is SELECT COUNT(*) with no other columns
    if query_type == "list" and _has_count(generated_sql):
        non_count_cols = {c for c in select_cols
                         if c not in {"count", "total", "cnt", "num"}}
        if not non_count_cols:
            issues.append(
                "Query type is 'list' but SQL only returns COUNT(*). "
                "Return individual rows with relevant columns instead."
            )

    # Rule 3: User mentions specific columns but they're absent from SELECT
    expected_cols: set[str] = set()
    for pat, cols in _KEYWORD_TO_COLUMNS:
        if pat.search(user_query):
            expected_cols.update(cols)

    if expected_cols and select_cols:
        # Check if at least one expected column is in SELECT
        found = expected_cols & select_cols
        if not found and query_type != "count":
            # Also check if any expected col appears anywhere in the SQL
            sql_lower = generated_sql.lower()
            any_in_sql = any(c in sql_lower for c in expected_cols)
            if not any_in_sql:
                issues.append(
                    f"User asked about {expected_cols} but none appear in "
                    f"the SELECT clause or elsewhere in the SQL."
                )

    # Rule 4: query_type="count" but SQL returns individual rows
    if query_type == "count" and not _has_count(generated_sql):
        issues.append(
            "Query type is 'count' but SQL does not use COUNT(). "
            "Return a COUNT query instead of individual rows."
        )

    # Build correction hints
    correction_hints = ""
    if issues:
        correction_hints = (
            "The following structural issues were detected:\n"
            + "\n".join(f"- {iss}" for iss in issues)
            + "\nPlease regenerate the SQL fixing these issues."
        )

    return {
        "sane": len(issues) == 0,
        "issues": issues,
        "correction_hints": correction_hints,
    }
