#!/usr/bin/env python3
"""Auto-generate safety/allowed_schema.yaml from the live database.

Introspects tables, views, columns, and foreign keys via graph.schema_parser
so the SQLGuard allowlist can never drift from the actual schema. Views
(e.g. formation_enthalpy) are included as first-class queryable relations.

Usage:
    python scripts/generate_allowed_schema.py [--check]

With --check, exits non-zero if the committed YAML differs from the live
schema (used as a sync test), without rewriting the file.
"""
from __future__ import annotations

import argparse
import os
import sys
from pathlib import Path

import psycopg

PROJECT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(PROJECT))

from graph.schema_parser import (  # noqa: E402
    get_foreign_keys,
    get_tables,
    introspect_schema,
)

OUT_PATH = PROJECT / "safety" / "allowed_schema.yaml"


def _conninfo() -> str:
    return (
        f"host={os.getenv('POSTGRES_HOST', 'localhost')} "
        f"port={os.getenv('POSTGRES_PORT', '5432')} "
        f"dbname={os.getenv('POSTGRES_DB', 'l12_materials')} "
        f"user={os.getenv('POSTGRES_USER', 'l12_user')} "
        f"password={os.getenv('POSTGRES_PASSWORD', 'l12_password')}"
    )


def render_yaml() -> str:
    with psycopg.connect(_conninfo()) as conn:
        meta = introspect_schema(conn)
        views = sorted(
            set(get_tables(conn, include_views=True))
            - set(get_tables(conn, include_views=False))
        )
        fks = get_foreign_keys(conn)

    lines: list[str] = []
    lines.append(
        "# AUTO-GENERATED by scripts/generate_allowed_schema.py — do not edit by hand."
    )
    lines.append(
        "# Regenerate after any schema change; tests verify sync with the live DB."
    )
    n_tables = len(meta["tables"]) - len(views)
    lines.append(f"# {n_tables} base tables + {len(views)} view(s).")
    lines.append("")
    lines.append("allowed_tables:")
    for t in meta["tables"]:
        suffix = "  # view" if t in views else ""
        lines.append(f"  - {t}{suffix}")
    lines.append("")
    lines.append("allowed_columns:")
    for t in meta["tables"]:
        for col in meta["columns"][t]:
            lines.append(f"  - {t}.{col.column_name}")
    lines.append("")
    lines.append("allowed_joins:")
    seen: set[tuple[str, str, str, str]] = set()
    for fk in fks:
        key = (fk.source_table, fk.source_column, fk.target_table, fk.target_column)
        if key in seen:
            continue
        seen.add(key)
        lines.append(f"  - source_table: {fk.source_table}")
        lines.append(f"    source_column: {fk.source_column}")
        lines.append(f"    target_table: {fk.target_table}")
        lines.append(f"    target_column: {fk.target_column}")
        lines.append("")
    return "\n".join(lines).rstrip() + "\n"


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--check", action="store_true", help="verify sync only")
    args = parser.parse_args()

    content = render_yaml()
    if args.check:
        current = OUT_PATH.read_text(encoding="utf-8") if OUT_PATH.exists() else ""
        if current != content:
            print("allowed_schema.yaml is OUT OF SYNC with the live database.")
            print("Run: python scripts/generate_allowed_schema.py")
            return 1
        print("allowed_schema.yaml is in sync with the live database.")
        return 0

    OUT_PATH.write_text(content, encoding="utf-8")
    print(f"Wrote {OUT_PATH}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
