#!/bin/bash
# POTCAR generation for SQS_RECALC_2x2x2
if [ -z "$VASP_PP_PATH" ]; then
    echo "Error: set VASP_PP_PATH"; exit 1; fi
PP_DIR="$VASP_PP_PATH/potpaw_PBE"

cat "$PP_DIR"/Ag/POTCAR > BCC_PURE/Ag8Ag8/POTCAR
cat "$PP_DIR"/Au/POTCAR > BCC_PURE/Au8Au8/POTCAR
cat "$PP_DIR"/Be/POTCAR > BCC_PURE/Be8Be8/POTCAR
cat "$PP_DIR"/Ca_sv/POTCAR > BCC_PURE/Ca8Ca8/POTCAR
cat "$PP_DIR"/Cr_pv/POTCAR > BCC_PURE/Cr8Cr8/POTCAR
cat "$PP_DIR"/Cr_pv/POTCAR > BCC_PURE/Cr8Cr8_AF/POTCAR
cat "$PP_DIR"/Fe_pv/POTCAR > BCC_PURE/Fe8Fe8/POTCAR
cat "$PP_DIR"/Ir/POTCAR > BCC_PURE/Ir8Ir8/POTCAR
cat "$PP_DIR"/Mn_pv/POTCAR > BCC_PURE/Mn8Mn8/POTCAR
cat "$PP_DIR"/Mn_pv/POTCAR > BCC_PURE/Mn8Mn8_AF/POTCAR
cat "$PP_DIR"/Os_pv/POTCAR > BCC_PURE/Os8Os8/POTCAR
cat "$PP_DIR"/Pb_d/POTCAR > BCC_PURE/Pb8Pb8/POTCAR
cat "$PP_DIR"/Pd/POTCAR > BCC_PURE/Pd8Pd8/POTCAR
cat "$PP_DIR"/Pt/POTCAR > BCC_PURE/Pt8Pt8/POTCAR
cat "$PP_DIR"/Re_pv/POTCAR > BCC_PURE/Re8Re8/POTCAR
cat "$PP_DIR"/Rh_pv/POTCAR > BCC_PURE/Rh8Rh8/POTCAR
cat "$PP_DIR"/Ru_pv/POTCAR > BCC_PURE/Ru8Ru8/POTCAR
cat "$PP_DIR"/Sn_d/POTCAR > BCC_PURE/Sn8Sn8/POTCAR
cat "$PP_DIR"/Ag/POTCAR "$PP_DIR"/Pb_d/POTCAR > BCC_MISSING/Ag8Pb8/POTCAR
cat "$PP_DIR"/Al/POTCAR "$PP_DIR"/Pb_d/POTCAR > BCC_MISSING/Al8Pb8/POTCAR
cat "$PP_DIR"/Al/POTCAR "$PP_DIR"/Pt/POTCAR > BCC_MISSING/Al8Pt8/POTCAR
cat "$PP_DIR"/Al/POTCAR "$PP_DIR"/Sn_d/POTCAR > BCC_MISSING/Al8Sn8/POTCAR
cat "$PP_DIR"/Au/POTCAR "$PP_DIR"/Mo_pv/POTCAR > BCC_MISSING/Au8Mo8/POTCAR
cat "$PP_DIR"/Au/POTCAR "$PP_DIR"/Ni_pv/POTCAR > BCC_MISSING/Au8Ni8/POTCAR
cat "$PP_DIR"/Au/POTCAR "$PP_DIR"/Pb_d/POTCAR > BCC_MISSING/Au8Pb8/POTCAR
cat "$PP_DIR"/Au/POTCAR "$PP_DIR"/Re_pv/POTCAR > BCC_MISSING/Au8Re8/POTCAR
cat "$PP_DIR"/Be/POTCAR "$PP_DIR"/Pb_d/POTCAR > BCC_MISSING/Be8Pb8/POTCAR
cat "$PP_DIR"/Ca_sv/POTCAR "$PP_DIR"/Co/POTCAR > BCC_MISSING/Ca8Co8/POTCAR
cat "$PP_DIR"/Ca_sv/POTCAR "$PP_DIR"/Os_pv/POTCAR > BCC_MISSING/Ca8Os8/POTCAR
cat "$PP_DIR"/Ca_sv/POTCAR "$PP_DIR"/Pb_d/POTCAR > BCC_MISSING/Ca8Pb8/POTCAR
cat "$PP_DIR"/Ca_sv/POTCAR "$PP_DIR"/Rh_pv/POTCAR > BCC_MISSING/Ca8Rh8/POTCAR
cat "$PP_DIR"/Ca_sv/POTCAR "$PP_DIR"/V_sv/POTCAR > BCC_MISSING/Ca8V8/POTCAR
cat "$PP_DIR"/Co/POTCAR "$PP_DIR"/Mn_pv/POTCAR > BCC_MISSING/Co8Mn8/POTCAR
cat "$PP_DIR"/Co/POTCAR "$PP_DIR"/Pb_d/POTCAR > BCC_MISSING/Co8Pb8/POTCAR
cat "$PP_DIR"/Cr_pv/POTCAR "$PP_DIR"/Pb_d/POTCAR > BCC_MISSING/Cr8Pb8/POTCAR
cat "$PP_DIR"/Cr_pv/POTCAR "$PP_DIR"/Pd/POTCAR > BCC_MISSING/Cr8Pd8/POTCAR
cat "$PP_DIR"/Cr_pv/POTCAR "$PP_DIR"/Pt/POTCAR > BCC_MISSING/Cr8Pt8/POTCAR
cat "$PP_DIR"/Cu_pv/POTCAR "$PP_DIR"/Pb_d/POTCAR > BCC_MISSING/Cu8Pb8/POTCAR
cat "$PP_DIR"/Cu_pv/POTCAR "$PP_DIR"/Sn_d/POTCAR > BCC_MISSING/Cu8Sn8/POTCAR
cat "$PP_DIR"/Fe_pv/POTCAR "$PP_DIR"/Pb_d/POTCAR > BCC_MISSING/Fe8Pb8/POTCAR
cat "$PP_DIR"/Hf_pv/POTCAR "$PP_DIR"/Pb_d/POTCAR > BCC_MISSING/Hf8Pb8/POTCAR
cat "$PP_DIR"/Hf_pv/POTCAR "$PP_DIR"/Sc_sv/POTCAR > BCC_MISSING/Hf8Sc8/POTCAR
cat "$PP_DIR"/Ir/POTCAR "$PP_DIR"/Pb_d/POTCAR > BCC_MISSING/Ir8Pb8/POTCAR
cat "$PP_DIR"/Ir/POTCAR "$PP_DIR"/Sn_d/POTCAR > BCC_MISSING/Ir8Sn8/POTCAR
cat "$PP_DIR"/Mg_pv/POTCAR "$PP_DIR"/Pb_d/POTCAR > BCC_MISSING/Mg8Pb8/POTCAR
cat "$PP_DIR"/Mn_pv/POTCAR "$PP_DIR"/Os_pv/POTCAR > BCC_MISSING/Mn8Os8/POTCAR
cat "$PP_DIR"/Mn_pv/POTCAR "$PP_DIR"/Pb_d/POTCAR > BCC_MISSING/Mn8Pb8/POTCAR
cat "$PP_DIR"/Mo_pv/POTCAR "$PP_DIR"/Pb_d/POTCAR > BCC_MISSING/Mo8Pb8/POTCAR
cat "$PP_DIR"/Ni_pv/POTCAR "$PP_DIR"/Pb_d/POTCAR > BCC_MISSING/Ni8Pb8/POTCAR
cat "$PP_DIR"/Ni_pv/POTCAR "$PP_DIR"/Pt/POTCAR > BCC_MISSING/Ni8Pt8/POTCAR
cat "$PP_DIR"/Ni_pv/POTCAR "$PP_DIR"/Sn_d/POTCAR > BCC_MISSING/Ni8Sn8/POTCAR
cat "$PP_DIR"/Os_pv/POTCAR "$PP_DIR"/Pb_d/POTCAR > BCC_MISSING/Os8Pb8/POTCAR
cat "$PP_DIR"/Pb_d/POTCAR "$PP_DIR"/Pd/POTCAR > BCC_MISSING/Pb8Pd8/POTCAR
cat "$PP_DIR"/Pb_d/POTCAR "$PP_DIR"/Pt/POTCAR > BCC_MISSING/Pb8Pt8/POTCAR
cat "$PP_DIR"/Pb_d/POTCAR "$PP_DIR"/Re_pv/POTCAR > BCC_MISSING/Pb8Re8/POTCAR
cat "$PP_DIR"/Pb_d/POTCAR "$PP_DIR"/Rh_pv/POTCAR > BCC_MISSING/Pb8Rh8/POTCAR
cat "$PP_DIR"/Pb_d/POTCAR "$PP_DIR"/Ru_pv/POTCAR > BCC_MISSING/Pb8Ru8/POTCAR
cat "$PP_DIR"/Pb_d/POTCAR "$PP_DIR"/Sn_d/POTCAR > BCC_MISSING/Pb8Sn8/POTCAR
cat "$PP_DIR"/Pb_d/POTCAR "$PP_DIR"/Ta_pv/POTCAR > BCC_MISSING/Pb8Ta8/POTCAR
cat "$PP_DIR"/Pb_d/POTCAR "$PP_DIR"/V_sv/POTCAR > BCC_MISSING/Pb8V8/POTCAR
cat "$PP_DIR"/Pb_d/POTCAR "$PP_DIR"/W_sv/POTCAR > BCC_MISSING/Pb8W8/POTCAR
cat "$PP_DIR"/Pb_d/POTCAR "$PP_DIR"/Zr_sv/POTCAR > BCC_MISSING/Pb8Zr8/POTCAR
cat "$PP_DIR"/Pd/POTCAR "$PP_DIR"/Re_pv/POTCAR > BCC_MISSING/Pd8Re8/POTCAR
cat "$PP_DIR"/Pt/POTCAR "$PP_DIR"/Re_pv/POTCAR > BCC_MISSING/Pt8Re8/POTCAR
cat "$PP_DIR"/Pt/POTCAR "$PP_DIR"/Sn_d/POTCAR > BCC_MISSING/Pt8Sn8/POTCAR
cat "$PP_DIR"/Re_pv/POTCAR "$PP_DIR"/Ru_pv/POTCAR > BCC_MISSING/Re8Ru8/POTCAR
cat "$PP_DIR"/Re_pv/POTCAR "$PP_DIR"/Sn_d/POTCAR > BCC_MISSING/Re8Sn8/POTCAR
cat "$PP_DIR"/Sc_sv/POTCAR "$PP_DIR"/Sn_d/POTCAR > BCC_MISSING/Sc8Sn8/POTCAR
cat "$PP_DIR"/Sn_d/POTCAR "$PP_DIR"/Zn/POTCAR > BCC_MISSING/Sn8Zn8/POTCAR
cat "$PP_DIR"/Mg_pv/POTCAR "$PP_DIR"/Pt/POTCAR > BCC_HIGHDEV/Mg8Pt8/POTCAR
cat "$PP_DIR"/Mg_pv/POTCAR "$PP_DIR"/Os_pv/POTCAR > BCC_HIGHDEV/Mg8Os8/POTCAR
cat "$PP_DIR"/Mg_pv/POTCAR "$PP_DIR"/Ni_pv/POTCAR > BCC_HIGHDEV/Mg8Ni8/POTCAR
cat "$PP_DIR"/Ca_sv/POTCAR "$PP_DIR"/Nb_pv/POTCAR > BCC_HIGHDEV/Ca8Nb8/POTCAR
cat "$PP_DIR"/Fe_pv/POTCAR "$PP_DIR"/Sn_d/POTCAR > BCC_HIGHDEV/Fe8Sn8/POTCAR
cat "$PP_DIR"/Rh_pv/POTCAR "$PP_DIR"/Sc_sv/POTCAR > BCC_HIGHDEV/Rh8Sc8/POTCAR
cat "$PP_DIR"/Ca_sv/POTCAR "$PP_DIR"/Zr_sv/POTCAR > BCC_HIGHDEV/Ca8Zr8/POTCAR
cat "$PP_DIR"/Co/POTCAR "$PP_DIR"/Sn_d/POTCAR > BCC_HIGHDEV/Co8Sn8/POTCAR
cat "$PP_DIR"/Be/POTCAR "$PP_DIR"/Ir/POTCAR > BCC_HIGHDEV/Be8Ir8/POTCAR
cat "$PP_DIR"/Fe_pv/POTCAR "$PP_DIR"/Mg_pv/POTCAR > BCC_HIGHDEV/Fe8Mg8/POTCAR
cat "$PP_DIR"/Ca_sv/POTCAR "$PP_DIR"/Mo_pv/POTCAR > BCC_HIGHDEV/Ca8Mo8/POTCAR
cat "$PP_DIR"/Be/POTCAR "$PP_DIR"/Pd/POTCAR > BCC_HIGHDEV/Be8Pd8/POTCAR
cat "$PP_DIR"/Be/POTCAR "$PP_DIR"/Os_pv/POTCAR > BCC_HIGHDEV/Be8Os8/POTCAR
cat "$PP_DIR"/Be/POTCAR "$PP_DIR"/Rh_pv/POTCAR > BCC_HIGHDEV/Be8Rh8/POTCAR
cat "$PP_DIR"/Be/POTCAR "$PP_DIR"/Re_pv/POTCAR > BCC_HIGHDEV/Be8Re8/POTCAR
cat "$PP_DIR"/Be/POTCAR "$PP_DIR"/Co/POTCAR > BCC_HIGHDEV/Be8Co8/POTCAR
cat "$PP_DIR"/Mg_pv/POTCAR "$PP_DIR"/V_sv/POTCAR > BCC_HIGHDEV/Mg8V8/POTCAR
cat "$PP_DIR"/Al/POTCAR "$PP_DIR"/Fe_pv/POTCAR > BCC_HIGHDEV/Al8Fe8/POTCAR
cat "$PP_DIR"/Be/POTCAR "$PP_DIR"/W_sv/POTCAR > BCC_HIGHDEV/Be8W8/POTCAR
cat "$PP_DIR"/Nb_pv/POTCAR > FCC_PURE/Nb16Nb16/POTCAR
cat "$PP_DIR"/Os_pv/POTCAR > FCC_PURE/Os16Os16/POTCAR
cat "$PP_DIR"/Pb_d/POTCAR > FCC_PURE/Pb16Pb16/POTCAR
cat "$PP_DIR"/Pd/POTCAR > FCC_PURE/Pd16Pd16/POTCAR
cat "$PP_DIR"/Pt/POTCAR > FCC_PURE/Pt16Pt16/POTCAR
echo "Done: 93 POTCARs."
