Console.sh 01.tcm &
Console.sh 02.tcm &
Console.sh 03.tcm &
Console.sh 04.tcm &
Console.sh 05.tcm &
Console.sh 06.tcm &
Console.sh 07.tcm &
Console.sh 08.tcm &
Console.sh 09.tcm &
Console.sh 10.tcm &
Console.sh 11.tcm &
Console.sh 12.tcm &
Console.sh 13.tcm &
Console.sh 14.tcm &
Console.sh 15.tcm &
Console.sh 16.tcm &
Console.sh 17.tcm &
Console.sh 18.tcm &
Console.sh 19.tcm &
Console.sh 20.tcm &
Console.sh 21.tcm &
Console.sh 22.tcm &
Console.sh 23.tcm &
Console.sh 24.tcm &
Console.sh 25.tcm &
Console.sh 26.tcm &
Console.sh 27.tcm &
Console.sh 28.tcm &
Console.sh 29.tcm &
Console.sh 30.tcm &
Console.sh 31.tcm &
Console.sh 32.tcm &
Console.sh 33.tcm &
Console.sh 34.tcm &
Console.sh 35.tcm &
Console.sh 36.tcm &
Console.sh 37.tcm &
Console.sh 38.tcm &
Console.sh 39.tcm &
Console.sh 40.tcm &
Console.sh 41.tcm &
Console.sh 42.tcm &
Console.sh 43.tcm &
Console.sh 44.tcm &
Console.sh 45.tcm &
Console.sh 46.tcm &
Console.sh 47.tcm &
Console.sh 48.tcm &
Console.sh 49.tcm &
Console.sh 50.tcm &
Console.sh 51.tcm &
Console.sh 52.tcm &
Console.sh 53.tcm &
Console.sh 54.tcm &
Console.sh 55.tcm &
Console.sh 56.tcm &
Console.sh 57.tcm &
Console.sh 58.tcm &
Console.sh 59.tcm &
Console.sh 60.tcm &
Console.sh 61.tcm &
Console.sh 62.tcm &
Console.sh 63.tcm &
Console.sh 64.tcm &
Console.sh 65.tcm &
Console.sh 66.tcm &
Console.sh 67.tcm &

