par(mfrow = c(3,1))

system("dakota_restart_util print dakota.rst   | grep err >  obj_func.dat" )
dat00 <-  read.table("obj_func.dat")
plot(log(dat00$V1), ylab="LOG [obj. func.]", type="l"); grid()

system("dakota_restart_util print dakota.rst   | grep V001 >  obj_func_V001.dat" )
dat01 <-  read.table("obj_func_V001.dat")
system("dakota_restart_util print dakota.rst   | grep V002 >  obj_func_V002.dat" )
dat02 <-  read.table("obj_func_V002.dat")
system("dakota_restart_util print dakota.rst   | grep V003 >  obj_func_V003.dat" )
dat03 <-  read.table("obj_func_V003.dat")
system("dakota_restart_util print dakota.rst   | grep V004 >  obj_func_V004.dat" )
dat04 <-  read.table("obj_func_V004.dat")
system("dakota_restart_util print dakota.rst   | grep V005 >  obj_func_V005.dat" )
dat05 <-  read.table("obj_func_V005.dat")
system("dakota_restart_util print dakota.rst   | grep V006 >  obj_func_V006.dat" )
dat06 <-  read.table("obj_func_V006.dat")
system("dakota_restart_util print dakota.rst   | grep V007 >  obj_func_V007.dat" )
dat07 <-  read.table("obj_func_V007.dat")
system("dakota_restart_util print dakota.rst   | grep V008 >  obj_func_V008.dat" )
dat08 <-  read.table("obj_func_V008.dat")
system("dakota_restart_util print dakota.rst   | grep V009 >  obj_func_V009.dat" )
dat09 <-  read.table("obj_func_V009.dat")
system("dakota_restart_util print dakota.rst   | grep V010 >  obj_func_V010.dat" )
dat10 <-  read.table("obj_func_V010.dat")


y_lim=c(-250e4,30e4)
plot((dat01$V1), ylab="V001", type="l", ylim=y_lim, col=1); par(new=T)
plot((dat02$V1), ylab="V002", type="l", ylim=y_lim, col=2); par(new=T)
plot((dat03$V1), ylab="V003", type="l", ylim=y_lim, col=3); par(new=T)
plot((dat04$V1), ylab="V004", type="l", ylim=y_lim, col=4); par(new=T)
plot((dat05$V1), ylab="V005", type="l", ylim=y_lim, col=5); par(new=T)
plot((dat06$V1), ylab="V006", type="l", ylim=y_lim, col=6); par(new=T)
plot((dat07$V1), ylab="V007", type="l", ylim=y_lim, col=7); par(new=T)
plot((dat08$V1), ylab="V008", type="l", ylim=y_lim, col=8); par(new=T)
plot((dat09$V1), ylab="V009", type="l", ylim=y_lim, col=9); par(new=T)
plot((dat10$V1), ylab="V010", type="l", ylim=y_lim, col=10); grid()


x_lim=c(-250e4,30e4)
plot(dat01$V1,dat00$V1, xlab="V001", ylab="Obj.Fun.", type="p", xlim=x_lim, col=1); par(new=T)
plot(dat02$V1,dat00$V1, xlab="V002", ylab="Obj.Fun.", type="p", xlim=x_lim, col=2); par(new=T)
plot(dat03$V1,dat00$V1, xlab="V003", ylab="Obj.Fun.", type="p", xlim=x_lim, col=3); par(new=T)
plot(dat04$V1,dat00$V1, xlab="V004", ylab="Obj.Fun.", type="p", xlim=x_lim, col=4); par(new=T)
plot(dat05$V1,dat00$V1, xlab="V005", ylab="Obj.Fun.", type="p", xlim=x_lim, col=5); par(new=T)
plot(dat06$V1,dat00$V1, xlab="V006", ylab="Obj.Fun.", type="p", xlim=x_lim, col=6); par(new=T)
plot(dat07$V1,dat00$V1, xlab="V007", ylab="Obj.Fun.", type="p", xlim=x_lim, col=7); par(new=T)
plot(dat08$V1,dat00$V1, xlab="V008", ylab="Obj.Fun.", type="p", xlim=x_lim, col=8); par(new=T)
plot(dat09$V1,dat00$V1, xlab="V009", ylab="Obj.Fun.", type="p", xlim=x_lim, col=9); par(new=T)
plot(dat10$V1,dat00$V1, xlab="V010", ylab="Obj.Fun.", type="p", xlim=x_lim, col=10); grid()


