services:
  postgres:
    image: postgres:15
    container_name: l12_postgres
    environment:
      POSTGRES_USER: l12_user
      POSTGRES_PASSWORD: l12_password
      POSTGRES_DB: l12_materials
    ports:
      - "5432:5432"
    volumes:
      - ../data/extended_schema.sql:/docker-entrypoint-initdb.d/01_schema.sql
      - ../data/02_seed_data.sql:/docker-entrypoint-initdb.d/02_seed_data.sql
      - ../data/seed:/seed
